Rails:
  Enabled: true

AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Capfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false